insight:
  enabled: false

database:
  host: shopscreen-db
  name: shopscreen
  user: shopscreen
  persistence:
    enabled: false

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

person:
  port: "3008"

company:
  port: "3009"
 
hostname: test-k8s-api-shopscreen.microsignage.com 