insight:
  enabled: false

database:
  host: shopscreen-db
  name: shopscreen
  user: shopscreen
  persistence:
    enabled: false

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
